### ISSUE TITLE
Not clear how to configure conjunctions of PDF settings

### ISSUE THREAD

**Issue by dannaf** [mtekman/ZoteroGoogleDrive-PDFLinker-Cloud#3]
The default `myconfig.conf` file lists:

```
[PDF Settings]
#  what to do with each pdf:
#  - any conjunction of attaching the pdf as a child item,
#    and/or overwriting or clearing the url field of the item
#  - valid modes are: attach_pdf, remove_pdf, url_set, url_clear
mode = attach_pdf
```

However, it is not clear to a new user how conjunctions are to be listed.  E.g., separated by a space?  or a comma?  or does it not matter?

Also, it is not clear if those multiple actions will be performed in order, or not.

\___

An example with multiple actions would help

**Comment by dannaf** [comment]
Spaces only doesn't work; commas work, or commas followed by spaces are fine too (since there's a `.strip()` happening, after the parse to list)

**Comment by mtekman** [comment]
Let's move this discussion to https://github.com/mtekman/ZoteroGoogleDrive-PDFLinker-Cloud/issues/6#issuecomment-514949963
